# Generated by Django 2.1.7 on 2019-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(default='Blog'),
        ),
    ]
